# Topic Modeling

##  (All Text)

In [1]:
import pandas as pd
import pickle

data = pd.read_pickle('pickle/dtm_stop.pkl')
data

,aaaaah,aaah,aah,abc,abcs,ability,abject,able,ablebodied,abortion,...,ze,zealand,zeppelin,zero,zillion,zombie,zombies,zoning,zoo,éclair
ali,0,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,2,...,0,10,0,0,0,0,0,0,0,0
bill,1,0,0,0,1,0,0,1,0,0,...,1,0,0,1,1,1,1,1,0,0
dave,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,3,0,0,0,0,1,0,0,...,0,0,0,2,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,2,1,0,0,0,0,0,0
ricky,0,0,0,0,0,1,1,2,0,0,...,0,0,0,0,0,0,0,0,1,0

In [2]:

from gensim import matutils, models
import scipy.sparse

C:\Users\Asus\Anaconda3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)

In [3]:
tdm = data.transpose()
tdm.head()

        ali  anthony  bill  dave  jim  joe  john  louis  mike  ricky
aaaaah    0        0     1     0    0    0     0      0     0      0
aaah      0        0     0     1    0    0     0      0     0      0
aah       0        0     0     0    0    0     0      3     0      0
abc       1        0     0     0    0    0     0      0     0      0
abcs      0        0     1     0    0    0     0      0     0      0

In [4]:
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [5]:
cv = pickle.load(open("pickle/cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

In [6]:
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.012*"fucking" + 0.008*"yeah" + 0.007*"went" + 0.006*"said" + 0.006*"going" + 0.006*"shit" + 0.005*"thing" + 0.005*"fuck" + 0.005*"say" + 0.005*"theyre"'),
 (1,
  '0.009*"said" + 0.006*"shit" + 0.006*"cause" + 0.005*"theyre" + 0.005*"really" + 0.005*"say" + 0.005*"didnt" + 0.004*"good" + 0.004*"oh" + 0.004*"yeah"')]

In [7]:
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.011*"fucking" + 0.009*"said" + 0.008*"yeah" + 0.007*"shit" + 0.006*"went" + 0.006*"fuck" + 0.006*"didnt" + 0.006*"say" + 0.005*"day" + 0.005*"thing"'),
 (1,
  '0.009*"said" + 0.007*"cause" + 0.005*"really" + 0.005*"shit" + 0.005*"says" + 0.005*"life" + 0.005*"hes" + 0.004*"thing" + 0.004*"theres" + 0.004*"yeah"'),
 (2,
  '0.007*"fcking" + 0.007*"fck" + 0.007*"theyre" + 0.005*"cause" + 0.005*"oh" + 0.005*"shit" + 0.005*"said" + 0.005*"say" + 0.005*"house" + 0.004*"little"')]

In [8]:
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.005*"said" + 0.005*"oh" + 0.005*"shit" + 0.005*"cause" + 0.005*"day" + 0.005*"little" + 0.004*"clinton" + 0.004*"hey" + 0.004*"lot" + 0.004*"mom"'),
 (1,
  '0.010*"said" + 0.008*"fucking" + 0.007*"shit" + 0.007*"yeah" + 0.006*"theyre" + 0.006*"didnt" + 0.005*"theres" + 0.005*"hes" + 0.005*"say" + 0.005*"thing"'),
 (2,
  '0.001*"say" + 0.001*"said" + 0.000*"thing" + 0.000*"fucking" + 0.000*"joke" + 0.000*"didnt" + 0.000*"yeah" + 0.000*"theyre" + 0.000*"hes" + 0.000*"day"'),
 (3,
  '0.008*"joke" + 0.008*"said" + 0.006*"anthony" + 0.006*"day" + 0.006*"say" + 0.005*"guys" + 0.005*"tell" + 0.004*"grandma" + 0.004*"thing" + 0.004*"good"')]

These topics aren't looking too great. We've tried modifying our parameters. Let's try modifying our terms list as well.

##  (Nouns Only)

In [9]:
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [10]:
data_clean = pd.read_pickle('pickle/data_clean.pkl')
data_clean

                                                transcript
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
bill      all right thank you thank you very much thank...
dave     this is dave he tells dirty jokes for a living...
jim         ladies and gentlemen please welcome to the ...
joe         ladies and gentlemen welcome joe rogan  wha...
john     armed with boyish charm and a sharp wit the fo...
louis    introfade the music out lets roll hold there l...
mike     wow hey thank you thanks thank you guys hey se...
ricky    hello hello how you doing great thank you wow ...

In [11]:
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i em i francisco city world...
bill     thank thank pleasure georgia area oasis i june...
dave     jokes living stare work profound train thought...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fck thanks phone fckface ...
john     charm wit snl writer john mulaney marriage bee...
louis    music lets lights lights thank i i place place...
mike     wow hey thanks look insane years everyone i id...
ricky    hello thank fuck thank im gon youre weve money...

In [12]:
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'fuck','fcking','jenny','fck','fucking','uh','ahah','aah','mm'
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said','dude','everybody',
                  'anybody','joke','hello','louis', 'dave', 'ricky', 'bill', 'jim', 'john', 'ali',
                  'anthony', 'mike', 'joe']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn

,abc,abcs,ability,abortion,abortions,abuse,accent,accents,access,accident,...,yulin,yummy,ze,zealand,zeppelin,zillion,zombie,zombies,zoo,éclair
ali,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,2,0,0,1,0,0,0,...,0,0,0,10,0,0,0,0,0,0
bill,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,1,1,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,1,0,2,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,0,0,0,2,1,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,15,...,0,0,0,0,2,0,0,0,0,0
ricky,0,0,1,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,1,0

In [13]:
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [14]:
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.008*"day" + 0.006*"thing" + 0.005*"school" + 0.005*"family" + 0.005*"grandma" + 0.005*"jokes" + 0.004*"baby" + 0.004*"youre" + 0.004*"lot" + 0.004*"money"'),
 (1,
  '0.015*"youre" + 0.010*"thing" + 0.009*"shit" + 0.009*"day" + 0.008*"cause" + 0.008*"man" + 0.008*"hes" + 0.008*"life" + 0.007*"way" + 0.007*"guy"')]

In [15]:
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.011*"day" + 0.010*"youre" + 0.010*"thing" + 0.007*"things" + 0.007*"years" + 0.006*"jokes" + 0.006*"id" + 0.005*"hes" + 0.005*"way" + 0.004*"money"'),
 (1,
  '0.008*"way" + 0.008*"cause" + 0.008*"youre" + 0.007*"man" + 0.007*"night" + 0.006*"shit" + 0.006*"guy" + 0.006*"day" + 0.005*"kind" + 0.005*"point"'),
 (2,
  '0.019*"youre" + 0.012*"shit" + 0.012*"thing" + 0.010*"life" + 0.010*"day" + 0.010*"cause" + 0.009*"man" + 0.009*"guy" + 0.008*"hes" + 0.008*"gon"')]

In [16]:
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.009*"day" + 0.009*"shit" + 0.008*"way" + 0.008*"man" + 0.007*"youre" + 0.007*"lot" + 0.007*"thing" + 0.006*"mom" + 0.006*"dad" + 0.006*"money"'),
 (1,
  '0.014*"youre" + 0.010*"day" + 0.008*"thing" + 0.007*"hes" + 0.007*"years" + 0.007*"shit" + 0.007*"lot" + 0.006*"god" + 0.005*"id" + 0.005*"woman"'),
 (2,
  '0.017*"youre" + 0.012*"cause" + 0.012*"thing" + 0.010*"life" + 0.009*"day" + 0.009*"guy" + 0.008*"man" + 0.008*"way" + 0.007*"gon" + 0.007*"hes"'),
 (3,
  '0.017*"youre" + 0.014*"shit" + 0.009*"guy" + 0.009*"gon" + 0.009*"thing" + 0.008*"hes" + 0.007*"man" + 0.007*"life" + 0.006*"day" + 0.006*"kid"')]

##  (Nouns and Adjectives)

In [17]:
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [18]:
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                transcript
ali      ladies gentlemen welcome stage ali wong hi wel...
anthony  thank san francisco thank good people surprise...
bill     right thank thank pleasure greater atlanta geo...
dave     dirty jokes living stare most hard work profou...
jim      ladies gentlemen welcome stage mr jim jefferie...
joe      ladies gentlemen joe fck san francisco thanks ...
john     boyish charm sharp wit former snl writer john ...
louis    music lets lights lights thank much i i i nice...
mike     wow hey thanks hey seattle nice look crazy ins...
ricky    hello great thank fuck thank lovely welcome im...

In [19]:
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,aaaaah,abc,abcs,ability,abject,able,ablebodied,abortion,abortions,absolute,...,yummy,yyou,ze,zealand,zeppelin,zillion,zombie,zombies,zoo,éclair
ali,0,1,0,0,0,2,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,2,0,0,...,0,0,0,10,0,0,0,0,0,0
bill,1,0,1,0,0,1,0,0,0,1,...,0,0,1,0,0,1,1,1,0,0
dave,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,1,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
ricky,0,0,0,1,1,2,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [20]:
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [21]:
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.005*"kid" + 0.004*"different" + 0.004*"water" + 0.003*"course" + 0.003*"weird" + 0.003*"men" + 0.003*"dick" + 0.003*"nuts" + 0.002*"lets" + 0.002*"gay"'),
 (1,
  '0.004*"mom" + 0.004*"kid" + 0.003*"family" + 0.003*"sure" + 0.003*"ass" + 0.003*"friend" + 0.003*"clinton" + 0.003*"okay" + 0.003*"girl" + 0.003*"parents"')]

In [22]:
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.005*"kid" + 0.005*"clinton" + 0.004*"mom" + 0.004*"different" + 0.003*"okay" + 0.003*"water" + 0.003*"cow" + 0.003*"president" + 0.003*"girl" + 0.003*"parents"'),
 (1,
  '0.005*"men" + 0.004*"sure" + 0.004*"guns" + 0.004*"son" + 0.004*"friend" + 0.004*"girl" + 0.003*"class" + 0.003*"ass" + 0.003*"phone" + 0.003*"gay"'),
 (2,
  '0.006*"kid" + 0.005*"ok" + 0.004*"family" + 0.004*"gun" + 0.004*"course" + 0.003*"mom" + 0.003*"husband" + 0.003*"tit" + 0.003*"grandma" + 0.003*"dead"')]

In [33]:
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=200)
ldana.print_topics()

[(0,
  '0.008*"husband" + 0.007*"ok" + 0.006*"pregnant" + 0.005*"asian" + 0.004*"fingers" + 0.004*"doo" + 0.004*"wan" + 0.004*"mom" + 0.004*"toilet" + 0.003*"body"'),
 (1,
  '0.007*"clinton" + 0.005*"parents" + 0.005*"friend" + 0.005*"mom" + 0.004*"cow" + 0.004*"wife" + 0.004*"phone" + 0.004*"sure" + 0.003*"accident" + 0.003*"idea"'),
 (2,
  '0.006*"men" + 0.005*"girl" + 0.005*"different" + 0.005*"guns" + 0.004*"ass" + 0.004*"son" + 0.004*"kid" + 0.004*"water" + 0.003*"dick" + 0.003*"gay"'),
 (3,
  '0.006*"kid" + 0.004*"course" + 0.004*"dead" + 0.004*"nuts" + 0.004*"jokes" + 0.004*"family" + 0.003*"hell" + 0.003*"gun" + 0.003*"tit" + 0.003*"okay"')]

These four topics look pretty decent. Let's settle on these for now.
* Topic 0: husband, pregnant
* Topic 1: parents, Freinds, 
* Topic 2: men, girl, guns
* Topic 3: kid, family

In [35]:
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(0, 'ali'),
 (3, 'anthony'),
 (3, 'bill'),
 (2, 'dave'),
 (2, 'jim'),
 (2, 'joe'),
 (1, 'john'),
 (3, 'louis'),
 (1, 'mike'),
 (3, 'ricky')]

For a first pass of LDA, these kind of make sense to me, so we'll call it a day for now.
* Topic 0: husband, pregnant [Ali]
* Topic 1: parents, Friends [ John, Mike]
* Topic 2: men,girl,guns [Dave, Joe, Jim]
* Topic 3: Kid,Family[Anthony, Bill, Louis, Ricky]